-- Temporarily disable RLS to test connection
-- This allows us to verify the database is working

ALTER TABLE organizations DISABLE ROW LEVEL SECURITY;
ALTER TABLE users DISABLE ROW LEVEL SECURITY;
ALTER TABLE nfc_devices DISABLE ROW LEVEL SECURITY;
ALTER TABLE events DISABLE ROW LEVEL SECURITY;
ALTER TABLE attendees DISABLE ROW LEVEL SECURITY;
ALTER TABLE nfc_scans DISABLE ROW LEVEL SECURITY;
ALTER TABLE content_bundles DISABLE ROW LEVEL SECURITY;
ALTER TABLE landing_pages DISABLE ROW LEVEL SECURITY;
ALTER TABLE analytics_events DISABLE ROW LEVEL SECURITY;
ALTER TABLE subscriptions DISABLE ROW LEVEL SECURITY;
ALTER TABLE white_label_configs DISABLE ROW LEVEL SECURITY;
